image: alpine/edge
packages:
  - go
  # Required by codecov
  - bash
  - findutils
sources:
  - https://github.com/mschneider82/go-smtp
tasks:
  - build: |
      cd go-smtp
      go build -v ./...
  - test: |
      cd go-smtp
      go test -coverprofile=coverage.txt -covermode=atomic ./...
  - upload-coverage: |
      cd go-smtp
      export CODECOV_TOKEN=2763beaa-33e8-4392-a49a-7a93ffb71c97
      curl -s https://codecov.io/bash | bash
